### ISSUE TITLE
BugFix: SFEMP3Shield.cpp:25:37: error: variable 'bitrate_table' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

### ISSUE THREAD

**Issue by Ac0lyte** [madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library#8]
Hello,

When going to compile I got the following error:

SFEMP3Shield.cpp:25:37: error: variable 'bitrate_table' must be const in order to be put into read-only section by means of '**attribute**((progmem))'

The fix was to add the 'const' keyword to line 25 so :

PROGMEM uint16_t bitrate_table[15][6] = {

becomes:

PROGMEM const uint16_t bitrate_table[15][6] = {

Thanks for the fantastic library!
- Tim

**Comment by webdevbrian** [comment]
Getting this same error. Arduino v 1.6.5, OSX El Capitan. Lilypad mp3

**Comment by mpflaga** [comment]
I was just able to compile using IDE 1.6.6 and fresh pull of this library. I recall several month back compiling 1.6.5, just fine for this. Although I found significant other (unrelated) bugs, so I left that version ASAP.

This error is about the version of compiler not liking the "PROGMEM" command, which has since been corrected in this repo.Note that with windows the Arduino's GCC complier is supplied with the IDE. However with Linux and Mac version of compiler may be updated separately. 

Please pull an update to the Repo to correct the problem.

FYI - I was just able to compile against recent SdFat 20150324 and the SFEMP3Shield supplied SdFat 20131225.
